# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Color Compass
tagline:          'Direction to Color'
description:      'Arduino program to convert compass heading from an ST LSM303 to a color to display on an RGB LED.'
url:              http://raritet.github.io/ColorCompass
baseurl:          http://username.github.io/poole/

author:
  name:           'Andy Oliver'
  url:            https://www.andy-oliver.com

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/raritet/ColorCompass
