# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Color Compass
tagline:          'Direction to Color'
description:      'Conveying direction in a fun, ambient way.'
url:              http://raritet.github.io/ColorCompass/
baseurl:          http://raritet.github.io/ColorCompass/

author:
  name:           'Andy Oliver'
  url:            https://www.andy-oliver.com

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/raritet/ColorCompass
